name: Mindgard Security Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MINDGARD_API_KEY: ${{ secrets.MINDGARD_API_KEY }}

jobs:
  Mindgard-Security-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install mindgard package
        run: python -m pip install --upgrade mindgard

      - name: Run mindgard test
        run: mindgard sandbox mistral --risk-threshold 90
